domain: suyashc.me       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://suyashc.me  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /suyashc.me/docs/      # place folder name if the site is served in a subfolder
